server:
  port: 8769
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/albedo-wzx/spring_cloud_config
          search-paths: config_file
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



